### ISSUE TITLE
Nvidia GPUs not being detected

### ISSUE THREAD

**Issue by dxvsh** [kserve/kserve#4722]
/kind bug

**What steps did you take and what happened:**
I tried making a deployment requesting a GPU in the resources (e.g. `nvidia.com/gpu: "1"`) but I observed that the GPU was not detected (neither on vLLM nor the HuggingFace backend). Relevant section of the logs:

```
DEBUG 10-01 12:03:47 [__init__.py:76] Exception happens when checking CUDA platform: NVML Shared Library Not Found
DEBUG 10-01 12:03:47 [__init__.py:93] CUDA platform is not available because: NVML Shared Library Not Found
INFO 10-01 13:17:36 [__init__.py:243] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 10-01 12:03:47 [_custom_ops.py:21] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
```

**What did you expect to happen:**
I expected my GPUs to be detected normally and be able to use them for inferencing. On Kserve, I'm stuck with only CPU for now. If I remove the `nvidia.com/gpu: 1` request for the GPUs, it works fine on the CPU as expected but not on the GPUs.

When I try using vLLM's official image for deploying a model without using KServe at all, it always detects my GPUs properly so this was quite a bit surprising for me since KServe is also using the vLLM backend.

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  creationTimestamp: "2025-10-01T13:04:37Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: qwen-llm
  namespace: test-ai
  resourceVersion: "1038086398"
  uid: 772532de-7411-4ebe-a638-3c58f24ed683
spec:
  predictor:
    model:
      args:
      - --model_name=qwen
      env:
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
      modelFormat:
        name: huggingface
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      storageUri: hf://Qwen/Qwen2.5-0.5B-Instruct
    nodeSelector:
      kubernetes.io/hostname: gpu
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
status:
  address:
    url: http://qwen-llm-predictor.test-ai.svc.cluster.local
  components:
    predictor:
      url: http://qwen-llm-predictor-test-ai.ai.ifad.org
  conditions:
  - lastTransitionTime: "2025-10-01T13:16:51Z"
    reason: Predictor ingress not created
    status: "False"
    type: IngressReady
  - lastTransitionTime: "2025-10-01T13:16:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: PredictorReady
  - lastTransitionTime: "2025-10-01T13:16:53Z"
    reason: Predictor ingress not created
    status: "False"
    type: Ready
  deploymentMode: RawDeployment
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    lastFailureInfo:
      exitCode: 1
      reason: ModelLoadFailed
    states:
      activeModelState: Loaded
      targetModelState: Loading
    transitionStatus: InProgress
  observedGeneration: 3
  url: http://qwen-llm-test-ai.example.com
```

**Anything else you would like to add:**

I'm also including the complete logs (with VLLM DEBUG mode enabled) if it helps:

```
INFO 10-01 12:03:46 [importing.py:53] Triton module has been replaced with a placeholder.
DEBUG 10-01 12:03:46 [__init__.py:28] No plugins for group vllm.platform_plugins found.
DEBUG 10-01 12:03:46 [__init__.py:34] Checking if TPU platform is available.
DEBUG 10-01 12:03:46 [__init__.py:44] TPU platform is not available because: No module named 'libtpu'
DEBUG 10-01 12:03:46 [__init__.py:52] Checking if CUDA platform is available.
DEBUG 10-01 12:03:47 [__init__.py:76] Exception happens when checking CUDA platform: NVML Shared Library Not Found
DEBUG 10-01 12:03:47 [__init__.py:93] CUDA platform is not available because: NVML Shared Library Not Found
DEBUG 10-01 12:03:47 [__init__.py:100] Checking if ROCm platform is available.
DEBUG 10-01 12:03:47 [__init__.py:114] ROCm platform is not available because: No module named 'amdsmi'
DEBUG 10-01 12:03:47 [__init__.py:122] Checking if HPU platform is available.
DEBUG 10-01 12:03:47 [__init__.py:129] HPU platform is not available because habana_frameworks is not found.
DEBUG 10-01 12:03:47 [__init__.py:140] Checking if XPU platform is available.
DEBUG 10-01 12:03:47 [__init__.py:150] XPU platform is not available because: No module named 'intel_extension_for_pytorch'
DEBUG 10-01 12:03:47 [__init__.py:158] Checking if CPU platform is available.
DEBUG 10-01 12:03:47 [__init__.py:180] Checking if Neuron platform is available.
DEBUG 10-01 12:03:47 [__init__.py:187] Neuron platform is not available because: No module named 'transformers_neuronx'
INFO 10-01 12:03:47 [__init__.py:243] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 10-01 12:03:47 [_custom_ops.py:21] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
DEBUG 10-01 12:03:49 [__init__.py:28] No plugins for group vllm.general_plugins found.
2025-10-01 12:03:49.312 1 kserve INFO [storage.py:download():64] Copying contents of /mnt/models to local
2025-10-01 12:03:49.312 1 kserve INFO [storage.py:download():110] Successfully copied /mnt/models to None
2025-10-01 12:03:49.312 1 kserve INFO [storage.py:download():111] Model downloaded in 0.00011201901361346245 seconds.
2025-10-01 12:03:49.328 1 kserve INFO [model_server.py:register_model():402] Registering model: qwen
2025-10-01 12:03:49.328 1 kserve INFO [model_server.py:setup_event_loop():282] Setting max asyncio worker threads as 32
2025-10-01 12:03:49.350 1 kserve INFO [server.py:_register_endpoints():108] OpenAI endpoints registered
2025-10-01 12:03:49.350 1 kserve INFO [server.py:start():161] Starting uvicorn with 1 workers
2025-10-01 12:03:49.390 1 uvicorn.error INFO:     Started server process [1]
2025-10-01 12:03:49.390 1 uvicorn.error INFO:     Waiting for application startup.
2025-10-01 12:03:49.394 1 kserve INFO [server.py:start():70] Starting gRPC server with 4 workers
2025-10-01 12:03:49.394 1 kserve INFO [server.py:start():71] Starting gRPC server on [::]:8081
2025-10-01 12:03:49.394 1 uvicorn.error INFO:     Application startup complete.
2025-10-01 12:03:49.395 1 uvicorn.error ERROR:    Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/kserve-workspace/kserve/kserve/model_server.py", line 297, in _serve
    await asyncio.gather(*self.servers)
  File "/kserve-workspace/huggingfaceserver/huggingfaceserver/vllm/vllm_model.py", line 112, in start_engine
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/kserve-workspace/huggingfaceserver/huggingfaceserver/vllm/utils.py", line 87, in build_async_engine_client_from_engine_args
    vllm_config = engine_args.create_engine_config(usage_context=usage_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1098, in create_engine_config
    device_config = DeviceConfig(device=self.device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/vllm/config.py", line 2119, in __post_init__
    raise RuntimeError(
RuntimeError: Failed to infer device type, please set the environment variable `VLLM_LOGGING_LEVEL=DEBUG` to turn on verbose logging to help debug the issue.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/starlette/routing.py", line 699, in lifespan
    await receive()
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2025-10-01 12:03:49.396 1 kserve ERROR [__main__.py:<module>():322] Failed to start model server: Failed to infer device type, please set the environment variable `VLLM_LOGGING_LEVEL=DEBUG` to turn on verbose logging to help debug the issue.
Traceback (most recent call last):
  File "/kserve-workspace/huggingfaceserver/huggingfaceserver/__main__.py", line 318, in <module>
    model_server.start([model])
  File "/kserve-workspace/kserve/kserve/model_server.py", line 340, in start
    asyncio.run(self._serve())
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/kserve-workspace/kserve/kserve/model_server.py", line 297, in _serve
    await asyncio.gather(*self.servers)
  File "/kserve-workspace/huggingfaceserver/huggingfaceserver/vllm/vllm_model.py", line 112, in start_engine
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/kserve-workspace/huggingfaceserver/huggingfaceserver/vllm/utils.py", line 87, in build_async_engine_client_from_engine_args
    vllm_config = engine_args.create_engine_config(usage_context=usage_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1098, in create_engine_config
    device_config = DeviceConfig(device=self.device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/kserve-workspace/prod_venv/lib/python3.12/site-packages/vllm/config.py", line 2119, in __post_init__
    raise RuntimeError(
RuntimeError: Failed to infer device type, please set the environment variable `VLLM_LOGGING_LEVEL=DEBUG` to turn on verbose logging to help debug the issue.
Error in sys.excepthook:

Original exception was:
```

**Environment:**

- Istio Version: N/A (deployed without Istio)
- Knative Version: N/A (using Raw Deployment)
- KServe Version: v0.15.2
- Kubeflow version: N/A (standalone Kserve deployment)
- Cloud Environment: No cloud environment, On-prem setup
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): v1.32.5+rke2r1
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04.2 LTS

**Comment by CHFang731** [comment]
你好

**Comment by CHFang731** [comment]
Hello, I'd like to try to fix this issue🙋‍♂️.  I'm new to KServe and would like to contribute.

I'll first reproduce the issue and explore possible fixes or documentation improvements.

Thank you!

**Comment by spolti** [comment]
Thanks @CHFang731 !

**Comment by spolti** [comment]
assign @CHFang731

**Comment by jokestax** [comment]
Hi @dxvsh ,i used a k3s cluster with below configuration and it worked for me,i changed two things i add `runtimeClassName: nvidia` and in args i had to change to `--served-model-name=qwen` 

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen-llm4
  namespace: test-ai
spec:
  predictor:
    runtimeClassName: nvidia
    model:
      modelFormat:
        name: huggingface
      storageUri: hf://Qwen/Qwen2.5-0.5B-Instruct
      args:
        - --served-model-name=qwen
      env:
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
```
